export const GET_PROFILE = 'GET_PROFILE';
export const RESET_PROFILE = 'RESET_PROFILE';
export const GET_PROFILE_MEMORIES = 'GET_PROFILE_MEMORIES';
export const CHANGE_PROFILE_AVATAR = 'CHANGE_PROFILE_AVATAR';
export const CHANGE_PROFILE_FIELD = 'CHANGE_PROFILE_FIELD';
